import dynamic from "next/dynamic";
import Head from "next/head";

const Footer = dynamic(() => import("@/components/footer"));
const Header = dynamic(() => import("@/components/header"));

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Next - PLN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="px-56 max-[1024px]:px-24 max-[425px]:px-6 py-10">
        {children}
      </main>
      <Footer />
    </>
  );
}
