name: Github CI

on:
  push:
    tags:
      - v**

jobs:
  run-build-prod:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && contains(github.ref_name, 'build_prod')
    steps:
      - name: Deploy over SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.193.178.126 >> ~/.ssh/known_hosts
          ls -la ~/.ssh