name: Github CI

on:
  push:
    tags:
      - v**

jobs:
  run-build-prod:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && contains(github.ref_name, 'build_prod')
    steps:
      - name: Running build app
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/next-pln/
            sudo git pull origin master
            pm2 restart home-pln
            pm2 list
